[package]
name = "ruby_object_with_rust"
version = "0.1.0"
authors = ["koyopro <koyopro2.0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[lib]
crate-type = ["cdylib"]
